rosrun pointcloud_orientation_estimation orientation_estimation_example _model:=`rospack find pointcloud_orientation_estimation`/learned_models/precise/top_down_multiclass_classifier.yaml _exampleFilesPath:=`rospack find pointcloud_orientation_estimation`/data/orientation_examples

